[WIP] Refactor refreshing to background, fix #4
Last-Order/Minyami-chrome-extension pull request #13
Opened 2020-07-08 18:22 UTC by CL-Jeremy

这次记住不在 commit 里面写 WIP 还不及时在设 ready for review 之前改掉 commit message 了……

图标颜色的设计是这样的：
1. 原本的冲淡的红色表示什么信息都没有，连 URL 都没有（即：无法检查是否属于支持的网站）
2. 明亮的红色代表 URL 不支持（原本想把这个颜色和 error 卡对应起来，后来觉得不太符合红绿灯的逻辑，但是具体方案还可以商量）
3. 黄色（可能不太明显）代表已经获得了至少一个信息（URL 支持、key、cookie、chunklist），等待进一步继续
4. 绿色当然是代表网站所需的信息已经全部抓取到了

因为要操作 canvas 对图标变色，我把图标直接放到了网页一个隐藏元素里，因为尝试了各种 async 的方案都很 ugly，为了尽量少对代码做无意义的改动，出此下策。

为了把整个刷新逻辑放到后台，不得不选择了大量的消息传递，虽然可以说比较照顾代码重用了，但是让易读性变得比较渣。当然还是那句话，都可以再改的。现在至少火狐和 Chromium 都是能用的状态了。

另外修改了一处逻辑：之前对 cookie 的警告卡是在 cookie 还没加载的时候显示，我觉得这个设计有点反常规，虽然不是不能理解但是我觉得还是有必要在全显示出来的时候也告知用户（另外这个警告卡也是我没有完全用图标颜色对应浮窗提示内容的原因，另一个原因是 Google 官方要求图标不要用灰度，否则和 Chromium 会和自己的扩展图标非活动状态发生混淆，本着用户基本也就关心绿和不绿这两个状态的思想弄成现在这样的）。

总之这么大的改动，还是先测试测试再看比较好，开个 branch 什么的也行。先感谢阅读。

2020-07-08 23:25 UTC, CL-Jeremy commented
发现这个版本非常神奇地解决了 Firefox 隐私浏览模式不能用和老版本显示不出图标的问题，太怪了 orz

2022-02-13 16:07 UTC, Last-Order commented
WIP好了吗.jpg

2022-02-17 16:47 UTC, CL-Jeremy commented
草，这么久了居然捞起来了，我还以为之前是没兴趣呢 orz
这一年半的迭代历程可得好好阅读一下……

2022-02-20 07:21 UTC, CL-Jeremy commented
这次不但按上面说的调转 cookie 警告卡的逻辑，还把之前吓到很多朋友的 Minyami 最低版本提示给改成灰色了，我相信他们不会忽略的（况且 2202 了谁还没更新啊除了我.jpg）
Manifest v3 用 service worker 以后没法从外部创立 Image 然后用 Canvas 渲染图标了，要么直接静态包含多个 assets，要么从头用 OfflineCanvas 绘制，干脆换成 badge 还可以每个分页保留独立状态，效果还可以（Edge 这个逗号加的有点无语就是了）

<img width="232" alt="Bildschirmfoto 2022-02-20 um 08 15 23" src="https://user-images.githubusercontent.com/1714243/154832716-55276983-8c91-4544-95eb-3db2aacd17ba.png">

<img width="230" alt="Bildschirmfoto 2022-02-20 um 08 16 14" src="https://user-images.githubusercontent.com/1714243/154832714-a62c0f83-0fdf-4528-8f46-c19e0a830a9a.png">

2022-02-20 15:19 UTC, Last-Order commented
@CL-Jeremy 不是没兴趣是之前不是一直标着WIP吗（
这个版本升级提示也有人跟我反应，我觉得可以换个文案

还有你这个1怎么看着不是很居中好难受（

2022-02-20 15:27 UTC, Last-Order requested changes

2022-02-20 15:27 UTC, Last-Order commented on src/pages/background/index.js
> +    console.log(tabToUrl[currentTab]);
不知道是啥的console删一下，或者加一下说明

2022-02-20 15:27 UTC, Last-Order commented on src/pages/background/index.js
> +const check = async () => {
您考虑换个更直白的函数名吗.jpg

2022-02-20 15:27 UTC, Last-Order commented on src/pages/config/index.vue
> +                Object.assign(this, message.detail);
别 Object.assign 到 this 上，太慌了
有啥赋值啥

2022-02-20 18:18 UTC, CL-Jeremy commented on src/pages/background/index.js
> +    console.log(tabToUrl[currentTab]);
应该是有一处以前是注释掉的，因为你恢复了一处，所以我这里也给忘掉改了（？）
肯定是不希望每次切换标签都会这样显示的，直接注释掉吧

2022-02-20 18:21 UTC, CL-Jeremy commented
> 还有你这个1怎么看着不是很居中好难受（

我也很绝望啊，我一开始 - 号还是用的西文破折号 – 结果显示得跟下划线一样，我都快哭了

2022-02-20 18:22 UTC, CL-Jeremy commented on src/pages/background/index.js
> +const check = async () => {
都是因为从 config 页面迁移过去的，而且这个 function 应该是不直接 call 的，我再改改

2022-02-21 01:17 UTC, CL-Jeremy commented on src/pages/background/index.js
> +    console.log(tabToUrl[currentTab]);
把监听 content script 的 console 也注释掉了，希望最终用户不需要用到

2022-02-21 09:24 UTC, CL-Jeremy commented
为什么非要纠结缓存在 content script 呢，原因是希望只要页面不刷新那所有 cookies 都保留在 Minyami Extractor 注入脚本加载时的命名空间里，将来看看能不能正式适配那些搞 history.pushState() 的网站（通过 [webNavigation.onHistoryStateUpdated()](https://developer.chrome.com/docs/extensions/reference/webNavigation/#event-onHistoryStateUpdated) 检测到以后删掉当前 script 元素重新注入）

2022-02-21 15:35 UTC, Last-Order requested changes
> 明亮的红色代表 URL 不支持
这个感觉看上去像是出了什么问题（实际上没有），有点太强烈了。
我的建议是，直接去掉，啥也不显示就好

2022-02-21 15:35 UTC, Last-Order commented on src/pages/config/index.vue
> +            if (message.type === "update_current") {
建议该Event更名为`set_state`，同理`query_current`更名为`get_state`。感觉比`current`容易理解……

2022-02-21 15:35 UTC, Last-Order commented on src/pages/config/index.vue
> +                notSupported: true
status可能有的其他几个字段给一个初始值。虽然整体更新`status`的写法下没问题，但是毕竟Vue2不能追踪property的增加，可能在未来埋坑。

2022-02-21 15:45 UTC, Last-Order commented on src/messages/en.js
> +        waiting: "Awaiting more data",
waiting for streams

2022-02-22 15:13 UTC, Last-Order commented
可以Merge了吗 我没啥问题了

2022-02-23 00:37 UTC, CL-Jeremy commented
绝了，居然没办法同时照顾 `window.onunload` 跟自定义事件，因为没有办法让窗口事件等扩展事件的回调

折腾了好半天才下定决心分情况处理成这个鬼样子了，这样可以保证关闭窗口的时候清除掉当前窗口 URL 对应的的本地存储，即使比如 URL 被动态加上了锚或者别的东西也不怕（当然如果本地存储不是以 URL 为键也许就不用这么麻烦了）

不过现在的效果很不错，多窗口时设置动态同步，Service Worker 重新唤醒甚至开关扩展也可以保证所有状态不丢，真正达到了后台透明加绿色的目的

顺便说下标签颜色的事：这个也是每家浏览器都不一样，我现在用 Opera 测试，这个默认主题下默认标贴颜色是统一的蓝色（Chromium 系需要设置背景色为 `#00000000` 来重设，Firefox 可以直接给 `null`）Firefox 官方文档上写了默认是红色，所以必须对状态进行初始化，有全局换色和标签独立换色两个选择，我看反正要处理重启 Service Worker 的问题就一气呵成了

现在就看什么时候 Firefox 鸽出 Manifest v3 支持了，不过 Chrome 也还有好多决定后面加 Promise 支持但还没 ship 的（Firefox 一开始就是自己提供 Promise，开发者自己选 `browser.*` 或 `chrome.*` namespace 来决定用哪种），到时候看弄成什么样吧

2022-02-23 00:51 UTC, CL-Jeremy commented on src/core/utils/storage.js
> +            });
这里是最后碰到的坑，检查了几遍自己的代码最后才发现源头（

2022-02-23 03:08 UTC, Last-Order commented on src/pages/background/index.js
> +            return url;
能不能解释下这啥原理？？addEventListener的回调不应该是异步的吗，为啥能保证先拿到url再返回？？

2022-02-23 03:13 UTC, CL-Jeremy commented on src/pages/background/index.js
> +            return url;
https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/dispatchEvent
> Unlike "native" events, which are fired by the browser and invoke event handlers asynchronously via the [event loop](https://developer.mozilla.org/en-US/docs/Web/JavaScript/EventLoop), `dispatchEvent()` invokes event handlers _synchronously_. All applicable event handlers are called and return before `dispatchEvent()` returns.

2022-02-23 03:15 UTC, Last-Order commented on src/pages/background/index.js
> +            return url;
原来如此，学到了。那这个地方为什么不能直接返回`location.href`而是要通过事件拿呢，都已经是在页面内执行脚本了。

2022-02-23 03:21 UTC, CL-Jeremy commented on src/pages/background/index.js
> +            return url;
`location.href` 就和直接后台取标签页 URL 没区别了吧，这里是确保 content script 和 service worker 都死掉以后还能保持第一次 init 时候的 URL，用来应对扩展禁用以后重新启用时不丢状态

2022-02-23 06:10 UTC, Last-Order commented on src/pages/background/index.js
> +            return url;
> 保持第一次 init 时候的 URL

你意思是禁用扩展之后页面URL发生变化，再启用仍能显示禁用之前获取到的流？但是如果URL发生了变化那理论上是不是也不应该展示之前的流了？

2022-02-23 07:45 UTC, CL-Jeremy commented on src/pages/background/index.js
> +            return url;
目前基本只有 `history.pushState` 等实际导致页面部分刷新的会受影响（如果 `inject_core.js` 被干掉就没关系了），我本意是如果页面上的 anchor 或 JavaScript 不刷新单纯编辑 URL 会导致和存储的数据脱节（还影响事后清理），所以我认为这么做利大于弊（毕竟谁会没事开关扩展以后还指望不刷新就能跟上最新状态，如果是单纯 Service Worker 的话上面说的事件会及时唤醒的，也就不存在抓不到部分刷新时机的问题）。另外现在这种部分刷新的本来就获取不到新的数据（除非想办法解除掉注入的所有影响然后重新注入，那又要改注入的那坨实际干活的代码了，懒.jpg）

2022-02-23 07:51 UTC, Last-Order commented on src/pages/background/index.js
> +            return url;
> 目前基本只有 history.pushState 等实际导致页面部分刷新的会受影响

其实这种网站很多，单页应用都是，目前Minyami支持的网站里Abema就是这个情况，你可以试下，目前就有问题，切换页面之后之前的流还在显示，区分不出来哪个是当前的（如果直接取location.href没问题，因为不是固定在初始URL）。

> 另外现在这种部分刷新的本来就获取不到新的数据
不会，SPA应用没有实际刷新页面，XHR注入一次可以持续生效。

2022-02-23 07:51 UTC, CL-Jeremy commented on src/pages/background/index.js
> +            return url;
像这样的还可以保证不会传一部分信息以后 URL 小改变导致另一部分信息存到了不同 URL 名下造成无法正常统合数据，这可比处理开关扩展那种有意义多了，那种更多是个 nice to have 的特性

2022-02-23 07:53 UTC, CL-Jeremy commented on src/pages/background/index.js
> +            return url;
> > 目前基本只有 history.pushState 等实际导致页面部分刷新的会受影响
> 
> 其实这种网站很多，单页应用都是，目前Minyami支持的网站里Abema就是这个情况，你可以试下，目前就有问题，切换页面之后之前的流还在显示，区分不出来哪个是当前的（如果直接取location.href没问题，因为不是固定在初始URL）。
> 
> > 另外现在这种部分刷新的本来就获取不到新的数据
> 
> 不会，SPA应用没有实际刷新页面，XHR注入一次可以持续生效。

行，那我知道有问题了，我自己是没碰到所以不清楚，至少 YouTube live 做不到

2022-02-23 07:58 UTC, Last-Order commented on src/pages/background/index.js
> +            return url;
> 像这样的还可以保证不会传一部分信息以后 URL 小改变导致另一部分信息存到了不同 URL 名下造成无法正常统合数据

或许可以考虑取 URL 的 pathname 部分？虽然可能还会有不按常理出牌的SPA应用把参数写query里，但应该是少数。（另外可能要考虑使用 hash mode 的 SPA 应用把 path 全写在 URL Hash 里的情况，感觉要处理这种的话坑越来越大了（

2022-02-23 08:10 UTC, CL-Jeremy commented on src/pages/background/index.js
> +            return url;
不大，我这里缓存的 URL 变量也不是死的（特意写的 `let`），后续变动随时都可以从工作代码逻辑那边设新的值，甚至如果要紧的话直接响应某些事件 notify 后台也行，建立好这些途径总是比想用却不好实现强。Manifest v3 堵了本地存储和会话存储 API 以后其实还有一个 Indexed DB 能用（似乎是 Service Worker 标配），相比之下现在这种传消息还是更干净的

2022-02-23 08:16 UTC, CL-Jeremy commented on src/pages/background/index.js
> +            return url;
总之如果有具体建议可以直接在 merge 的时候改或者给 fork 的这个 branch 提 PR，我还是理解尚浅，测试也可能不到点子上

2022-02-23 08:18 UTC, Last-Order commented on src/pages/background/index.js
> +            return url;
你还改吗，要不我先 Merge 了这个 PR 然后再慢慢改。

2022-02-23 08:24 UTC, CL-Jeremy commented on src/pages/background/index.js
> +            return url;
我是不太准备改的（之前的🚀就这个意思），Abema 我现在不熟了，也不太方便测试，所以具体业务代码不敢乱动
我这里本来就是想办法琢磨把迁移 v3 前的 `tabToUrl` 重新实现一遍，确定下来的话以后好改

2022-02-23 15:25 UTC, Last-Order commented
感谢你的 Pull Request！！

2022-02-23 15:25 UTC, merged

2022-02-23 15:51 UTC, Last-Order commented
关于 Abema 的那个问题，先保留了通过事件获取 URL 的方式，但是总是返回当前 URL 而非初始 URL。
后续在个别站点需要适配特别逻辑时候再改这个 URL 的返回逻辑。

整理一下先做个笔记。

在不重新加载页面的情况下 URL 变化分为两种
1. 改变 URL 但页面内容不变，例如增加 query 参数等。
2. 改变 URL 且页面内容发生变化，主要是单页应用通过 JavaScript Router 进行导航。

可能需要新增两个新的 message type。针对情况 1 将旧 URL 下数据迁移到新 URL。针对情况 2 视作新页面。